GET http://localhost:8080/employees

###

GET http://localhost:8080/employees/1

###

POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "HuMan",
  "lastName": "Odds"
}

###

PUT http://localhost:8080/employees/10
Content-Type: application/json

{
  "firstName": "Man",
  "lastName": "Odds"
}

###

DELETE http://localhost:8080/employees/1

###

GET http://localhost:8080/employees/query?lastName=Doe

###

GET http://localhost:8080/employees/nativeQuery
